### ISSUE TITLE
Can you share Code for Dataset Analysis

### ISSUE THREAD

**Issue by geyan21** [kerenfu/LFSOD-Survey#1]
I have trouble analyzing datasets like image center distance, focal slices and so on. Can you share your code for evaluating datasets?

**Comment by jiangyao-scu** [comment]
> I have trouble analyzing datasets like image center distance, focal slices and so on. Can you share your code for evaluating datasets?

Thanks for your attention to our work. I'm sorry, we didn't sort out this part of the code, but I can tell you how to implement it. Firstly, for the calculation of the object center, we used the ''CV2.Findcontours'' function to calculate the object contour, and then used ''CV2.Moments'' to estimate the center coordinates of the contour. For focal slices, we made statistics according to the rules of picture naming, and then drew the curves with MATLAB.

**Comment by geyan21** [comment]
Thanks for your reply! As I don't have much experience in Matlab coding, it's really exhausting for me to finish it in time. So is there any possibility that you can sort out the code for me? I know there is no reason for you to do that.

**Comment by jiangyao-scu** [comment]
蒋遥
996658807@qq.com



&nbsp;你好，你加我QQ吧，996658807，我QQ发你代码，因为代码是分开的，代码的使用还得交流，用QQ直接交流，方便一点。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kerenfu/LFSOD-Survey"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 晚上6:41
收件人:&nbsp;"kerenfu/LFSOD-Survey"<LFSOD-Survey@noreply.github.com&gt;;
抄送:&nbsp;"蒋遥"<996658807@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [kerenfu/LFSOD-Survey] Can you share Code for Dataset Analysis (#1)





 
Thanks for your reply! As I don't have much experience in Matlab coding, it's really exhausting for me to finish it in time. So is there any possibility that you can sort out the code for me? I know there is no reason for you to do that.

**Comment by zanyongqiang** [comment]
Dear author, thank you very much for your work. I have some questions to ask for your help. May I have your email?
