### ISSUE TITLE
The link of of DUTLF-MV is dead.

### ISSUE THREAD

**Issue by YumingWu97** [kerenfu/LFSOD-Survey#3]
The baiduyun link of DUTLF-MV is dead.Can you please re-share the expired link?

**Comment by jiangyao-scu** [comment]
Thank you for your attention to our work, and we have repaired the link of DUTLF-MV.

**Comment by YumingWu97** [comment]
It seems that DUTLF-MV only has views on vertical and horizontal lines instead of square views.
Is this normal？

**Comment by YumingWu97** [comment]
It seems that DUTLF-MV only has views on vertical and horizontal lines instead of square views.
How did you test MAC with it.

**Comment by jiangyao-scu** [comment]
We did not test MAC on DUTLF-MV. For the datasets that have no available micro-lens image arrays, we follow [1] and test MAC on single up-sampled all-in-focus images. More details can be found in the survey and benchmark.

[1] Zhang J, Liu Y, Zhang S, et al. Light field saliency detection with deep convolutional networks[J]. IEEE Transactions on Image Processing, 2020, 29: 4421-4434.

**Comment by YumingWu97** [comment]
Thanks for your reply.Your work is really helpful.
